/* eslint-disable redux-saga/yield-effects */
import { takeEvery, call, put } from 'redux-saga/effects';

import requestWithToken from 'utils/requestWithToken';
import {{ camelCase name }}Saga, { {{ camelCase name }}Worker } from '../saga';
import { INIT_DATA_REQUEST } from '../constants';
import { initSuccess, initFailure } from '../actions';

const data = { data: 'test data' };
const error = { message: 'test error' };


describe('{{ camelCase name }}Saga', () => {
  const gen = {{ camelCase name }}Saga();

  it('should wait for INIT_DATA_REQUEST', () => {
    expect(gen.next().value).toEqual(takeEvery(INIT_DATA_REQUEST, {{ camelCase name }}Worker));
  });

  it('should be done', () => {
    expect(gen.next()).toEqual({ done: true, value: undefined });
  });
});


describe('{{ camelCase name }}Worker', () => {
  const gen = {{ camelCase name }}Worker();

  it('should call the api', () => {
    expect(gen.next().value).toEqual(call(requestWithToken, 'TODO'));
  });

  it('should update the store with the api results', () => {
    expect(gen.next(data).value).toEqual(put(initSuccess(data)));
  });

  it('should be done', () => {
    expect(gen.next()).toEqual({ done: true, value: undefined });
  });

  it('should handle errors', () => {
    const errGen = {{ camelCase name }}Worker();
    errGen.next();
    expect(errGen.throw(error).value).toEqual(put(initFailure(error)));
    expect(errGen.next()).toEqual({ done: true, value: undefined });
  });
});
